name = "lendada/contracts"
version = "1.0.0"
license = "Apache-2.0"
description = "RealFi MicroLoan Smart Contracts"

[repository]
user = "lendada"
project = "contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
